### ISSUE TITLE
Bullets get cut at the side

### ISSUE THREAD

**Issue by marcustut** [marcustut/community-bot#1]
In commit 2c1fe7ea64fcebedb35d11244552dccf7fbd0027, I have taken out Green color values and changed the Background to Green with color code #00ff00, this to let OBS key better. But one issue is the Bullets now are appearing at all positions, mean it can get cut at the border sometimes.

**Screenshot**:
![image](https://user-images.githubusercontent.com/59773847/116510390-692edf00-a8f7-11eb-8c7b-94e6c1429064.png)

**Possible Solutions**:
1. Implement a new prop to the `StyledBullet` or `BulletScreen` components where it will force the bullets to be rendered in a specific area only
2. Make the <div> with class "screen" to only 50vh and center it and fill in the two spaces with other div.

**Comment by neosizzle** [comment]
Since youre using CSS, ever considered adding a wrapper container that has top and bottom padding?

**Comment by neosizzle** [comment]
Alright, i took a look at this issue and came up with a temporary slap on solution involving wrapping the screen around a container that has a green bg. the screen itself will be positioned absolutely to limit where the bullets can go.

Here is a working example of what I meant. The section in blue is where the actual screen is.  
![image](https://user-images.githubusercontent.com/44501267/116519094-a4370f80-a903-11eb-90c1-95b82efbf891.png)

Here is how it looks like on mobile devices:
![image](https://user-images.githubusercontent.com/44501267/116519302-eb250500-a903-11eb-98ea-1602e1983ded.png)

The screen above can be adjusted according to taste in the code.
I also eliminated the overflow so the scrollbars wont get in the way.

**Comment by marcustut** [comment]
Great, I think this was fixed then.
